# Mark L. 'Everything in a box'

version: '3.6'

services:
  keycloak_proxy:
    image: nginx:stable
    container_name: keycloak_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "443:443"
    depends_on:
      - keycloak_web
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  keycloak_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    env_file: .env
    environment:

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KC_DB_PASSWORD} # Ensure you update these variables in the .env file.
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT: true
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_HTTP_ENABLED: false
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/certs/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/certs/tls.key
      KC_PROXY: edge
      
      KC_TRANSACTION_XA_ENABLED: false
      KC_HTTP_RELATIVE_PATH: /auth
      JAVA_OPTS: "-Xms512m -Xmx2048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Dfile.encoding=UTF-8"

      KC_SPI_EVENTS_LISTENER_EMAIL_EXCLUDE_EVENTS: "LOGIN, LOGOUT"
      KC_LOG_LEVEL: WARN
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true

      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER} # Ensure you update these variables in the .env file.
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD} # Ensure you update these variables in the .env file.
    volumes:
      - ./certs:/opt/keycloak/conf/certs:ro
    command: start --optimized
    depends_on:
      keycloakdb:
        condition: service_healthy
    expose:
      - 8443
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
        reservations:
          memory: 1G
          cpus: '1'
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "https://localhost:8443/auth/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  keycloakdb:
    image: postgres:15
    container_name: keycloakdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
        reservations:
          memory: 512M
          cpus: '0.5'
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
    driver: local
